// Generated by CoffeeScript 1.6.1
(function() {
  var module;

  module = angular.module("code-snippet", []);

  module.directive("codeSnippet", function() {
    return {
      restrict: 'E',
      compile: function(element, attrs) {
        return element.html("<p>Un po' di codice:</p><pre>" + element.html() + "</pre>");
      }
    };
  });

}).call(this);
